services: 
  app:
    build: 
      context: ./FeedService/
      target: final
    ports: 
      - "8080:80"
    depends_on:
      - db
    
  db: 
    image: mcr.microsoft.com/mssql/server
    ports: 
      - "1433:1433"
    environment:
      SA_PASSWORD: "AnalKarnaval228$"
      ACCEPT_EULA: "Y"
